# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_biomassa(object):
    def setupUi(self, biomassa):
        biomassa.setObjectName("biomassa")
        biomassa.resize(731, 541)
        self.botao = QtWidgets.QDialogButtonBox(biomassa)
        self.botao.setGeometry(QtCore.QRect(520, 50, 161, 32))
        self.botao.setOrientation(QtCore.Qt.Horizontal)
        self.botao.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.botao.setObjectName("botao")
        self.caminho_pasta = QtWidgets.QLineEdit(biomassa)
        self.caminho_pasta.setGeometry(QtCore.QRect(110, 20, 571, 21))
        self.caminho_pasta.setObjectName("caminho_pasta")
        self.nome_shp = QtWidgets.QLineEdit(biomassa)
        self.nome_shp.setGeometry(QtCore.QRect(110, 50, 391, 21))
        self.nome_shp.setObjectName("nome_shp")
        self.grafico_tabela = QtWidgets.QGraphicsView(biomassa)
        self.grafico_tabela.setGeometry(QtCore.QRect(30, 90, 651, 421))
        self.grafico_tabela.setObjectName("grafico_tabela")
        self.label = QtWidgets.QLabel(biomassa)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(biomassa)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 91, 20))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(biomassa)
        self.botao.accepted.connect(biomassa.accept) # type: ignore
        self.botao.rejected.connect(biomassa.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(biomassa)

    def retranslateUi(self, biomassa):
        _translate = QtCore.QCoreApplication.translate
        biomassa.setWindowTitle(_translate("biomassa", "Dialog"))
        self.caminho_pasta.setText(_translate("biomassa", "X:/Sigmagis/VERTICAIS/COLABORADORES/Luan_Faria/MODELOS_QGIS/MODELO/CAMPO FURLAN/"))
        self.nome_shp.setText(_translate("biomassa", "BASE_TALHOES_NDVI_EXEMPLO.shp"))
        self.label.setText(_translate("biomassa", "CAMINHO"))
        self.label_2.setText(_translate("biomassa", "NOME DO SHP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    biomassa = QtWidgets.QDialog()
    ui = Ui_biomassa()
    ui.setupUi(biomassa)
    biomassa.show()
    sys.exit(app.exec_())
